name: Maven Package

on:
  release:
    types: [created]

services:
  mysql:
    image: mysql:latest
    env:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: air_companies
    ports:
      - 3306:3306
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Start MySQL Service
      run: docker-compose up -d mysql

    - name: Wait for MySQL to start
      run: docker-compose exec mysql mysqladmin --silent --wait=30 -uroot -p123456 ping

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests
      env:
        GITHUB_TOKEN: ${{ github.token }}
